const ultrahots2025 = [
    {
        "id": "hw-silver-2025-2025-6-1",
        "name": "'70 Ford Escort RS1600",
        "series": "Ultra Hots",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY60",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T33, T35, T37",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/1f/2025UH1-1_%28Large%29.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/2d/Ford_RS.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Ford_Escort_RS1600"
    },
    {
        "id": "hw-silver-2025-2025-6-2",
        "name": "Volkswagen T1-GTR",
        "series": "Ultra Hots",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY61",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T33, T35, T37, T39, T40, T42",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/75/JBY61.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/6f/VW_Bus.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_T1-GTR"
    },
    {
        "id": "hw-silver-2025-2025-6-3",
        "name": "'89 Mazda Savanna RX-7 FC3S",
        "series": "Ultra Hots",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY62",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T33, T37, T39, T40",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/ca/JBY62.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/82/3-8.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2789_Mazda_Savanna_RX-7_FC3S"
    },
    {
        "id": "hw-silver-2025-2025-6-4",
        "name": "'88 Honda CR-X",
        "series": "Ultra Hots",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY63",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T33, T35, T37, T39",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/ef/JBY63.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/01/CRX.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2788_Honda_CR-X"
    },
    {
        "id": "hw-silver-2025-2025-6-5",
        "name": "Porsche 356 Outlaw",
        "series": "Ultra Hots",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY64",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T33, T35, T36, T37, T39",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/45/JBY64.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/72/Amazing_Porsche.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Porsche_356_Outlaw"
    },
    {
        "id": "hw-silver-2025-2025-6-6",
        "name": "'65 Pontiac GTO",
        "series": "Ultra Hots",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY65",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T33, T37, T39",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/68/JBY65.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/89/Just_Another_GTO.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2765_Pontiac_GTO"
    },
    {
        "id": "hw-silver-2025-2025-6-7",
        "name": "'81 Toyota Starlet KP61",
        "series": "Ultra Hots",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY66",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T33, T37, T39",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/6c/JBY66.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/5/50/W_Toyota.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2781_Toyota_Starlet_KP61"
    },
    {
        "id": "hw-silver-2025-2025-6-8",
        "name": "'69 COPO Corvette",
        "series": "Ultra Hots",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY67",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T33, T35, T37, T39",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/26/JBY67.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/8c/20241127_012600.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2769_COPO_Corvette"
    }
];