const ultrahots2022 = [
{
        "id": "hw-silver-2022-Single Packs-0-1",
        "name": "'66 Ford Fairlane 427",
        "series": "Ultra Hots",
        "release": "Single Packs",
        "year": 2022,
        "toyId": "HDG61",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R02, R04",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/4d/Ultra_Hots_%2766_Ford_Fairlane_427_Deep_Purple_HDG61_2022_open.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/4f/Ultra_Hots_%2766_Ford_Fairlane_427_Deep_Purple_HDG61_2022.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2766_Ford_Fairlane_GT"
    },
    {
        "id": "hw-silver-2022-Single Packs-0-2",
        "name": "'69 Mercury Cyclone",
        "series": "Ultra Hots",
        "release": "Single Packs",
        "year": 2022,
        "toyId": "HDG62",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R02, R25",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/51/Ultra_Hots_%2769_Mercury_Cyclone_Zamac_HDG62_2022_open.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/f7/Ultra_Hots_%2769_Mercury_Cyclone_Zamac_HDG62_2022.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2769_Mercury_Cyclone"
    },
    {
        "id": "hw-silver-2022-Single Packs-0-3",
        "name": "'70 Plymouth Barracuda",
        "series": "Ultra Hots",
        "release": "Single Packs",
        "year": 2022,
        "toyId": "HDG63",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R02, R05",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/f4/Ultra_Hots_%2770_Plymouth_Barracuda_Purple_HDG63_2022_open.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/bc/Ultra_Hots_%2770_Plymouth_Barracuda_Purple_HDG63_2022.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Plymouth_Barracuda"
    },
    {
        "id": "hw-silver-2022-Single Packs-0-4",
        "name": "'80 El Camino",
        "series": "Ultra Hots",
        "release": "Single Packs",
        "year": 2022,
        "toyId": "HDG64",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/35/Ultra_Hots_%2780_El_Camino_Gold_HDG64_2022_open.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/9b/Ultra_Hots_%2780_El_Camino_Gold_HDG64_2022.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2780_El_Camino"
    },
    {
        "id": "hw-silver-2022-Single Packs-0-5",
        "name": "'71 Plymouth GTX",
        "series": "Ultra Hots",
        "release": "Single Packs",
        "year": 2022,
        "toyId": "HDG65",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R02, R04",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/5a/Ultra_Hots_%2771_Plymouth_GTX_Apple_Green_HDG65_2022_open.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/ab/Ultra_Hots_%2771_Plymouth_GTX_Apple_Green_HDG65_2022.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_Plymouth_GTX"
    },
    {
        "id": "hw-silver-2022-Single Packs-0-6",
        "name": "'70 Chevy Camaro RS",
        "series": "Ultra Hots",
        "release": "Single Packs",
        "year": 2022,
        "toyId": "HDG66",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c1/Ultra_Hots_%2770_Chevy_Camaro_RS_Deep_Blue_HDG66_2022_open.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/5/5d/Ultra_Hots_%2770_Chevy_Camaro_RS_Deep_Blue_HDG66_2022.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Chevy_Camaro_RS"
    },
    {
        "id": "hw-silver-2022-Single Packs-0-7",
        "name": "'87 Buick Regal GNX",
        "series": "Ultra Hots",
        "release": "Single Packs",
        "year": 2022,
        "toyId": "HDG67",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/0/06/Ultra_Hots_%2787_Buick_Regal_GNX_Deep_Red_HDG67_2022_open.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/f7/Ultra_Hots_%2787_Buick_Regal_GNX_Deep_Red_HDG67_2022.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2787_Buick_Regal_GNX"
    },
    {
        "id": "hw-silver-2022-Single Packs-0-8",
        "name": "'67 Oldsmobile 442",
        "series": "Ultra Hots",
        "release": "Single Packs",
        "year": 2022,
        "toyId": "HDG68",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/1d/Ultra_Hots_%2767_Oldsmobile_442_Red_HDG68_2022_open.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/6d/Ultra_Hots_%2767_Oldsmobile_442_Red_HDG68_2022.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2767_Oldsmobile_442"
    }
];