const ultrahots2023 = [
    {
        "id": "hw-silver-2023-Mix 1-2-1",
        "name": "'68 Mercury Cougar",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2023,
        "toyId": "HLH82",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R30, R31, R35",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/f9/%2768MercuryCougar.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/4d/HLH82.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2768_Mercury_Cougar_(2014)"
    },
    {
        "id": "hw-silver-2023-Mix 1-2-2",
        "name": "1974 Brazilian Dodge Charger",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2023,
        "toyId": "HLH86",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R30, R32, R35",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/a7/%2774BrazilianCharger.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/d3/HLH86.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/1974_Brazilian_Dodge_Charger"
    },
    {
        "id": "hw-silver-2023-Mix 1-2-3",
        "name": "'67 Shelby GT-500",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2023,
        "toyId": "HLH89",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R29, R30, R32, R35",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/10/%2767ShelbyGT500.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/98/HLH89.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2767_Shelby_GT500_(2008)"
    },
    {
        "id": "hw-silver-2023-Mix 1-2-4",
        "name": "Nissan Silvia (S14) Drift",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2023,
        "toyId": "HLH85",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R22, R29, R30, R31, R32, R34, R35",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/fd/TeamTordenSilvia.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/72/HLH85.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_Silvia_(S14)_Drift"
    },
    {
        "id": "hw-silver-2023-Mix 1-2-5",
        "name": "'70 Pontiac Firebird",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2023,
        "toyId": "HLH84",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R30, R32, R35",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/e9/GMachinesFirebird.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/3f/HLH84.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Pontiac_Firebird"
    },
    {
        "id": "hw-silver-2023-Mix 1-2-6",
        "name": "Honda Civic Si",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2023,
        "toyId": "HLH88",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R30, R32, R35",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b3/HondaCivicEM1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/18/HLH88.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Honda_Civic_Si_(2001)"
    },
    {
        "id": "hw-silver-2023-Mix 1-2-7",
        "name": "'71 Chevy El Camino",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2023,
        "toyId": "HLH83",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R29, R30, R32, R35",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/69/%2771ElCamino.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/2b/HLH83.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_El_Camino"
    },
    {
        "id": "hw-silver-2023-Mix 1-2-8",
        "name": "Volkswagen SP2",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2023,
        "toyId": "HLH87",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R30, R32, R35",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/5e/VolkswagenSP2.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/f1/HLH87.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_SP2"
    },
    {
        "id": "hw-silver-2023-Mix 2-3-1",
        "name": "'64 Chevy Chevelle SS",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2023,
        "toyId": "HLH93",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R49, S02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/8a/Ultra_loose_chevyish.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/6c/Ultra_Hots_64_Chevy_Chevelle_SS.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2764_Chevy_Chevelle_SS"
    },
    {
        "id": "hw-silver-2023-Mix 2-3-2",
        "name": "'68 Plymouth Barracuda Formula S",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2023,
        "toyId": "HLH94",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S02, S10",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/d9/07223555.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/75/Ultra_Hots_68_Plymouth_Barracuda_Formula_S.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2768_Plymouth_Barracuda_Formula_S"
    },
    {
        "id": "hw-silver-2023-Mix 2-3-3",
        "name": "'71 Dodge Demon",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2023,
        "toyId": "HLH91",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R49, S02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/6b/Ultra_loose_demon.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/eb/Ultra_Hots_71_Dodge_Demon.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_Dodge_Demon"
    },
    {
        "id": "hw-silver-2023-Mix 2-3-4",
        "name": "'71 Plymouth Road Runner",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2023,
        "toyId": "HLH95",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R49, S02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/25/20250425000826.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/27/Ultra_Hots_71_Plymouth_Road_Runner.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_Plymouth_Road_Runner"
    },
    {
        "id": "hw-silver-2023-Mix 2-3-5",
        "name": "'73 Ford Falcon XB",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2023,
        "toyId": "HLH90",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R49, S02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/30/Ultra_loose_falcon.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/2e/Ultra_Hots_2023_Mix_2_%2773_Ford_Falcon_XB_Red_Malaysia_HLH90.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2773_Ford_Falcon_XB"
    },
    {
        "id": "hw-silver-2023-Mix 2-3-6",
        "name": "Custom '69 Volkswagen Squareback",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2023,
        "toyId": "HLH92",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R39, S02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/e4/2023-Ultra_Hots_6-8_HLH92_%2769_Squareback_Zamak_ooref-1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/5/58/Ultra_Hots_Custom_69_Volkswagen_Squareback.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_%2769_Volkswagen_Squareback"
    },
    {
        "id": "hw-silver-2023-Mix 2-3-7",
        "name": "Nissan Fairlady Z",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2023,
        "toyId": "HLH97",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R45, R49, S02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c9/230621194434.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/44/Ultra_Hots_Nissan_Fairlady_Z.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_Fairlady_Z"
    },
    {
        "id": "hw-silver-2023-Mix 2-3-8",
        "name": "Porsche 934.5",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2023,
        "toyId": "HLH96",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R45, R49, S02",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b9/2023-Ultra_Hots_8-8_HLH96_R45_Porsche_934.5_Orange_open-1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/72/Ultra_Hots_Porsche_934.5.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Porsche_934.5"
    }
];