const ultrahots2024 = [
    {
        "id": "hw-silver-2024-Mix 1-4-1",
        "name": "'66 Pontiac GTO",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRX00",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S44, S48, S49, S50",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/dd/%2766_Pontiac_GTO_in_Spectraflame_Purple_2024_HotWheels_Ultra_Hots.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/c4/66_Pontiac_GTO_Ultra_Hots.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2766_Pontiac_GTO"
    },
    {
        "id": "hw-silver-2024-Mix 1-4-2",
        "name": "Triumph TR6",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRX01",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S44, S48, S49, S50",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/21/2024_Triumph_TR6.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/ec/Triumph_TR6_Ultra_Hots.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Triumph_TR6"
    },
    {
        "id": "hw-silver-2024-Mix 1-4-3",
        "name": "'71 AMC Javelin",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRX02",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S44, S48, S49, S50",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/3b/%2771_AMC_Javelin_in_Spectraflame_Blue_2024_HotWheels_Ultra_Hots.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/ba/71_AMC_Javelin.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_AMC_Javelin"
    },
    {
        "id": "hw-silver-2024-Mix 1-4-4",
        "name": "'73 BMW 3.0 CSL Race Car",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRX03",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S30, S44, S48, S50",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/57/%2773_BMW_3_0_CSL_Race_Car_in_Spectraflame_Black_202_HotWheels_Ultra_Hots.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/7a/2024-Ultra_Hots_HRX03_%2773_BMW_3.O_CSL_Race_Black_ref-1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2773_BMW_3.0_CSL_Race_Car"
    },
    {
        "id": "hw-silver-2024-Mix 1-4-5",
        "name": "Mazda REPU",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRX04",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S44, S48, S49, S50",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/d3/UltraHotsRepu2024.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/14/Ultra_Hots_2024_Mix_1_Mazda_Repu_Ice_Blue_Malaysia_HRX04.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Mazda_REPU"
    },
    {
        "id": "hw-silver-2024-Mix 1-4-6",
        "name": "80's Pontiac Firebird",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRX05",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S44, S48, S49, S50",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/8a/80%27s_Pontiac_Firebird_in_Spectraflame_Red_2024_HotWheels_Ultra_Hots.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/7c/20231117_212508.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2780s_Firebird"
    },
    {
        "id": "hw-silver-2024-Mix 1-4-7",
        "name": "'81 Ford Fairmont",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRX06",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S48, S50",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/27/%2781_Ford_Fairmont_in_Spectraflame_Dark_Teal_2024_HotWheels_Ultra_Hots.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/2a/Ultra_Hots_2024_Mix_1_%2781_Ford_Fairmont_Aqua_Malaysia_HRX06.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Frontrunnin%27_Fairmont"
    },
    {
        "id": "hw-silver-2024-Mix 1-4-8",
        "name": "Volkswagen Käfer Racer",
        "series": "Ultra Hots",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRX07",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S30, S44, S48, S49, S50",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/75/Volkswagen_K%C3%A4fer_Racer_in_Spectraflame_Gold_2024_HotWheels_Ultra_Hots.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/f5/2023-Ultra_Hots_HRX07_K%C3%A4fer_Racer_Gold_ref-1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_K%C3%A4fer_Racer"
    },
    {
        "id": "hw-silver-2024-Mix 2-5-1",
        "name": "'64 Dodge 330",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRX08",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T08, T11, T18",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b8/0240421231954.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/cb/20240421232051.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2764_Dodge_330"
    },
    {
        "id": "hw-silver-2024-Mix 2-5-2",
        "name": "'71 Datsun 510",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRX09",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T08, T11, T12, T18",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/87/20240421232008.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/75/20240421232030.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Datsun_Bluebird_510"
    },
    {
        "id": "hw-silver-2024-Mix 2-5-3",
        "name": "Nissan Skyline H/T 2000GT-X",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRX10",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T07, T11, T18",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/f5/20240421232017.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/15/20240421232043.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_Skyline_H/T_2000GT-X"
    },
    {
        "id": "hw-silver-2024-Mix 2-5-4",
        "name": "'78 Porsche 935-78",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRX11",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T08, T11, T18",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/79/20240421231958.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/ee/20240421232025.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2778_Porsche_935-78"
    },
    {
        "id": "hw-silver-2024-Mix 2-5-5",
        "name": "Toyota AE86 Sprinter Trueno",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRX12",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T07, T11, T18",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/7e/20240421232021.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/f3/20240421232047.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Toyota_AE86_Sprinter_Trueno"
    },
    {
        "id": "hw-silver-2024-Mix 2-5-6",
        "name": "'85 Honda City Turbo II",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRX13",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T07, T11, T18",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c6/20240421232013.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/ad/20240421232056.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2785_Honda_City_Turbo_II"
    },
    {
        "id": "hw-silver-2024-Mix 2-5-7",
        "name": "'86 Ford Thunderbird Pro Stock",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRX14",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T08, T11, T18",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/f9/20240421231941.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/d1/20240421232035.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2786_Ford_Thunderbird_Pro_Stock"
    },
    {
        "id": "hw-silver-2024-Mix 2-5-8",
        "name": "Custom Volkswagen Beetle",
        "series": "Ultra Hots",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRX15",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T07, T11, T12, T18",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c6/20240421232003.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/20240421232039.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_Volkswagen_Beetle"
    }
];