const spring2026 = [
    {
        "id": "hw-silver-2026-Spring-0-1",
        "name": "Ford Escort",
        "series": "Seasonal",
        "release": "Spring",
        "year": 2026,
        "toyId": "JKY37",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c7/EscortSpring26.jpeg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/65/JKY37-ND710.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Escort_Rally"
    },
    {
        "id": "hw-silver-2026-Spring-0-2",
        "name": "Cosmic Coupe",
        "series": "Seasonal",
        "release": "Spring",
        "year": 2026,
        "toyId": "JKY38",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/JKY38-ND710.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Cosmic_Coupe"
    },
    {
        "id": "hw-silver-2026-Spring-0-3",
        "name": "Geoterra",
        "series": "Seasonal",
        "release": "Spring",
        "year": 2026,
        "toyId": "JKY39",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/87/GeoterraSpring26.jpeg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/8f/JKY39-ND710.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Geoterra"
    },
    {
        "id": "hw-silver-2026-Spring-0-4",
        "name": "Driftsta",
        "series": "Seasonal",
        "release": "Spring",
        "year": 2026,
        "toyId": "JKY40",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/4b/DriftstaSpring26.jpeg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/45/JKY40-ND710.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Driftsta"
    },
    {
        "id": "hw-silver-2026-Spring-0-5",
        "name": "Dimachinni Veloce",
        "series": "Seasonal",
        "release": "Spring",
        "year": 2026,
        "toyId": "JKY41",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/94/DimachinniVeloceSpring26.jpeg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/16/JKY41-ND710.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Dimachinni_Veloce"
    }
];