const spiderman2026 = [
    {
        "id": "hw-silver-2026-Spider-Man-0-1",
        "name": "Cool-One",
        "series": "Entertainment",
        "release": "Spider-Man",
        "year": 2026,
        "toyId": "JKX25",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U38A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/73/Spiderman_Cool_One_loose.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/00/Silver_Series_2026_Spider-Man_Cool-One_Thailand_JKX25.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Cool-One"
    },
    {
        "id": "hw-silver-2026-Spider-Man-0-2",
        "name": "Ground FX",
        "series": "Entertainment",
        "release": "Spider-Man",
        "year": 2026,
        "toyId": "JKX26",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U38A, U41A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/30/Silver_Series_2026_Spider-Man_Ground_FX_Thailand_JKX26.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Ground_FX"
    },
    {
        "id": "hw-silver-2026-Spider-Man-0-3",
        "name": "Rogue Hog",
        "series": "Entertainment",
        "release": "Spider-Man",
        "year": 2026,
        "toyId": "JKX27",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Uses original tooling, Base code(s): U38A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/e5/2026Roguehog_Spiderman2.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/83/Silver_Series_2026_Spider-Man_Rogue_Hog_Thailand_JKX27.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Rogue_Hog"
    },
    {
        "id": "hw-silver-2026-Spider-Man-0-4",
        "name": "Fish'd & Chip'd",
        "series": "Entertainment",
        "release": "Spider-Man",
        "year": 2026,
        "toyId": "JKX28",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U38A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Silver_Series_2026_Spider-Man_Fish%27d_%26_Chip%27d_Thailand_JKX28.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Fish%27d_%26_Chip%27d"
    },
    {
        "id": "hw-silver-2026-Spider-Man-0-5",
        "name": "Combat Medic",
        "series": "Entertainment",
        "release": "Spider-Man",
        "year": 2026,
        "toyId": "JKX29",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U38A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/ac/Combat_Medic_Spiderman_loose.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/5/50/Silver_Series_2026_Spider-Man_Combat_Medic_Thailand_JKX29.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Combat_Medic"
    }
];