const toystory52026 = [
    {
        "id": "hw-silver-2026-Toy Story 5-0-1",
        "name": "Custom Volkswagen Beetle",
        "series": "Entertainment",
        "release": "Toy Story 5",
        "year": 2026,
        "toyId": "JKX30",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_Volkswagen_Beetle"
    },
    {
        "id": "hw-silver-2026-Toy Story 5-0-2",
        "name": "Fandango",
        "series": "Entertainment",
        "release": "Toy Story 5",
        "year": 2026,
        "toyId": "JKX31",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Fandango"
    },
    {
        "id": "hw-silver-2026-Toy Story 5-0-3",
        "name": "Grand Cross",
        "series": "Entertainment",
        "release": "Toy Story 5",
        "year": 2026,
        "toyId": "JKX32",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Grand_Cross"
    },
    {
        "id": "hw-silver-2026-Toy Story 5-0-4",
        "name": "MS-T Suzuka",
        "series": "Entertainment",
        "release": "Toy Story 5",
        "year": 2026,
        "toyId": "JKX33",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/MS-T_Suzuka"
    },
    {
        "id": "hw-silver-2026-Toy Story 5-0-5",
        "name": "Custom '77 Dodge Van",
        "series": "Entertainment",
        "release": "Toy Story 5",
        "year": 2026,
        "toyId": "JKX34",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_%2777_Dodge_Van"
    }
];