const a90sStreet2025 = [
    {
        "id": "hw-silver-2025-90s Street Scene-0-1",
        "name": "'96 Nissan 180SX Type X",
        "series": "Automative",
        "release": "90s Street Scene",
        "year": 2025,
        "toyId": "JCB57",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T30, T39, T41",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/cd/1996NissanRPS13.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/e5/%2796_Nissan_180SX_Type_X_Carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2796_Nissan_180SX_Type_X"
    },
    {
        "id": "hw-silver-2025-90s Street Scene-0-2",
        "name": "Mitsubishi Lancer Evolution VI",
        "series": "Automative",
        "release": "90s Street Scene",
        "year": 2025,
        "toyId": "JCB58",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "New Plastic Chassis, Base code(s): T30, T39, T41",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/62/2000EvoVI.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/00/Mitsubishi_Lancer_Evolution_VI_Carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Mitsubishi_Lancer_Evolution_VI"
    },
    {
        "id": "hw-silver-2025-90s Street Scene-0-3",
        "name": "Nissan 300ZX Twin Turbo",
        "series": "Automative",
        "release": "90s Street Scene",
        "year": 2025,
        "toyId": "JCB59",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T30, T41",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/92/1994Nissan300ZX.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/80/Nissan_300ZX_Twin_Turbo_Carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_300ZX_Twin_Turbo"
    },
    {
        "id": "hw-silver-2025-90s Street Scene-0-4",
        "name": "'95 Toyota Celica GT-Four",
        "series": "Automative",
        "release": "90s Street Scene",
        "year": 2025,
        "toyId": "JCB60",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T24, T30, T41",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/22/1995ToyotaGTFour.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/41/%2790s_Street_Scene_2025_%2795_Toyota_Celica_GT-Four_Silver_Malaysia_JCB60.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2795_Toyota_Celica_GT-Four"
    },
    {
        "id": "hw-silver-2025-90s Street Scene-0-5",
        "name": "'92 Honda Civic EG",
        "series": "Automative",
        "release": "90s Street Scene",
        "year": 2025,
        "toyId": "JCB56",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T30, T41",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/96/1992HondaEG6.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b1/%2790s_Street_Scene_2025_%2792_Honda_Civic_EG_Black_Malaysia_JCB56.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Honda_Civic_EG"
    }
];
