const hotwheelsjimports2024 = [
    {
        "id": "hw-silver-2024-Hot Wheels J-Imports-0-1",
        "name": "1968 Mazda Cosmo Sport",
        "series": "Automative",
        "release": "Hot Wheels J-Imports",
        "year": 2024,
        "toyId": "HRT00",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S45, T01, T04",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/5b/MazdaCosmo.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/9f/Hot_Wheels_J-Imports_2024_1968_Mazda_Cosmo_Sport_Orange_Malaysia_HRT00.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/1968_Mazda_Cosmo_Sport"
    },
    {
        "id": "hw-silver-2024-Hot Wheels J-Imports-0-2",
        "name": "Nissan Skyline HT 2000GT-X",
        "series": "Automative",
        "release": "Hot Wheels J-Imports",
        "year": 2024,
        "toyId": "HRT01",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S45, S47, T01, T04",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/91/1972NissanSkyline.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/29/Hot_Wheels_J-Imports_2024_Nissan_Skyline_HT_2000GT-X_Red_Malaysia_HRT01.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_Skyline_H/T_2000GT-X"
    },
    {
        "id": "hw-silver-2024-Hot Wheels J-Imports-0-3",
        "name": "'81 Toyota Starlet KP61",
        "series": "Automative",
        "release": "Hot Wheels J-Imports",
        "year": 2024,
        "toyId": "HRT02",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S37, T01, T02, T04",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/91/1981ToyotaStarlet.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/4b/Hot_Wheels_J-Imports_2024_%2781_Toyota_Starlet_KP61_Seafoam_Malaysia_HRT02.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2781_Toyota_Starlet_KP61"
    },
    {
        "id": "hw-silver-2024-Hot Wheels J-Imports-0-4",
        "name": "1985 Honda CR-X",
        "series": "Automative",
        "release": "Hot Wheels J-Imports",
        "year": 2024,
        "toyId": "HRT03",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S39, T01, T02, T04",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/e5/1985HondaCR-X.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/ff/Hot_Wheels_J-Imports_2024_1985_Honda_CR-X_Yellow_Malaysia_HRT03.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/1985_Honda_CR-X"
    },
    {
        "id": "hw-silver-2024-Hot Wheels J-Imports-0-5",
        "name": "Acura NSX",
        "series": "Automative",
        "release": "Hot Wheels J-Imports",
        "year": 2024,
        "toyId": "HRT04",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S45, T01, T03",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/89/HondaNSXGT500.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/88/Hot_Wheels_J-Imports_2024_Acura_NSX_Dark_Blue_Malaysia_HRT04.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Acura_NSX"
    }
];