const hotwagons2024 = [
    {
        "id": "hw-silver-2024-Hot Wagons-0-1",
        "name": "'64 Chevy Nova Wagon",
        "series": "Automative",
        "release": "Hot Wagons",
        "year": 2024,
        "toyId": "HRR89",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S31, S36, S37, S38, S40",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/11/NovaWagon.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/d2/HRR88.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2764_Chevy_Nova_Wagon"
    },
    {
        "id": "hw-silver-2024-Hot Wagons-0-2",
        "name": "Custom '66 GTO Wagon",
        "series": "Automative",
        "release": "Hot Wagons",
        "year": 2024,
        "toyId": "HRR87",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S30, S36, S37, S38, S40",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/0/08/GTOWagon.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/9a/HRR87.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_%2766_GTO_Wagon"
    },
    {
        "id": "hw-silver-2024-Hot Wagons-0-3",
        "name": "Datsun Bluebird Wagon (510)",
        "series": "Automative",
        "release": "Hot Wagons",
        "year": 2024,
        "toyId": "HRR88",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S33, S36, S37, S41",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c2/510Wagon.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/d7/HRR89.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_Datsun_Bluebird_510_Wagon"
    },
    {
        "id": "hw-silver-2024-Hot Wagons-0-4",
        "name": "Volvo 850 Estate",
        "series": "Automative",
        "release": "Hot Wagons",
        "year": 2024,
        "toyId": "HRR86",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S30, S36, S37, S40",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/41/Volvo850R.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/de/HRR86.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volvo_850_Estate"
    },
    {
        "id": "hw-silver-2024-Hot Wagons-0-5",
        "name": "'17 Audi RS 6 Avant",
        "series": "Automative",
        "release": "Hot Wagons",
        "year": 2024,
        "toyId": "HRR85",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S29, S36, S37, S38, S41, S42",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/85/AudiRS6.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/3b/HRR85.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2717_Audi_RS_6_Avant"
    }
];