const hwspeedgraphics2024 = [
    {
        "id": "hw-silver-2024-HW Speed Graphics-0-1",
        "name": "'99 Honda Civic Type R (EK9)",
        "series": "Automative",
        "release": "HW Speed Graphics",
        "year": 2024,
        "toyId": "HRT09",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T27",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/a6/FalkenEK9.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/95/HW_Speed_Graphics_2024_%2799_Honda_Civic_Type_R_%28EK9%29_Blue_Malaysia_HRT09.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2799_Honda_Civic_Type_R_(EK9)"
    },
    {
        "id": "hw-silver-2024-HW Speed Graphics-0-2",
        "name": "Range Rover Classic",
        "series": "Automative",
        "release": "HW Speed Graphics",
        "year": 2024,
        "toyId": "HRT08",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T26, T27",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b4/HRT08.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/de/HW_Speed_Graphics_2024_Range_Rover_Classic_White_Malaysia_HRT08.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Range_Rover_Classic"
    },
    {
        "id": "hw-silver-2024-HW Speed Graphics-0-3",
        "name": "Porsche 914 Safari",
        "series": "Automative",
        "release": "HW Speed Graphics",
        "year": 2024,
        "toyId": "HRT06",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T22, T24, T26, T27",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/4f/HRT06.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/07/HW_Speed_Graphics_2024_Porsche_914_Safari_Orange_Malaysia_HRT06.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Porsche_914_Safari"
    },
    {
        "id": "hw-silver-2024-HW Speed Graphics-0-4",
        "name": "Mazda RX-3",
        "series": "Automative",
        "release": "HW Speed Graphics",
        "year": 2024,
        "toyId": "HRT07",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T27",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/5d/HRT07.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/01/HW_Speed_Graphics_2024_Mazda_RX-3_Red_Malaysia_HRT07.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Mazda_RX-3"
    },
    {
        "id": "hw-silver-2024-HW Speed Graphics-0-5",
        "name": "Big-Air Bel-Air",
        "series": "Automative",
        "release": "HW Speed Graphics",
        "year": 2024,
        "toyId": "HRT05",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T26, T27",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/be/HRT05.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/30/Big-Air_Bel-Air.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Big-Air_Bel-Air"
    }
];