const hybridspeed2025 = [
    {
        "id": "hw-silver-2025-Hybrid Speed-0-1",
        "name": "BMW i8 Roadster",
        "series": "Automative",
        "release": "Hybrid Speed",
        "year": 2025,
        "toyId": "JCB76",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U20N, U21N, U23N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/de/JCB76_BMW_o1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/6a/Silver_Series_2025_Hybrid_Speed_BMW_i8_Roadster_Malaysia_JCB76.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/BMW_i8_Roadster"
    },
    {
        "id": "hw-silver-2025-Hybrid Speed-0-2",
        "name": "Lamborghini Sián FKP 37",
        "series": "Automative",
        "release": "Hybrid Speed",
        "year": 2025,
        "toyId": "JCB77",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U21N, U23N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/54/Hybrid_Speed_Series_%282%29.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/88/Silver_Series_2025_Hybrid_Speed_Lamborghini_Sian_FKP_37_Malaysia_JCB77.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Lamborghini_Si%C3%A1n_FKP_37"
    },
    {
        "id": "hw-silver-2025-Hybrid Speed-0-3",
        "name": "McLaren P1",
        "series": "Automative",
        "release": "Hybrid Speed",
        "year": 2025,
        "toyId": "JCB78",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U21N, U23N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c9/JCB78_McLaren_o1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/bc/Silver_Series_2025_Hybrid_Speed_McLaren_P1_Malaysia_JCB78.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/McLaren_P1"
    },
    {
        "id": "hw-silver-2025-Hybrid Speed-0-4",
        "name": "Porsche Panamera Turbo S E-Hybrid Sport Turismo",
        "series": "Automative",
        "release": "Hybrid Speed",
        "year": 2025,
        "toyId": "JCB79",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U21N, U23N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/f1/JCB79_LN_o1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/16/Silver_Series_2025_Hybrid_Speed_Porsche_Panamera_Turbo_S_E-Hybrid_Sport_Turismo_Malaysia_JCB79.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Porsche_Panamera_Turbo_S_E-Hybrid_Sport_Turismo"
    },
    {
        "id": "hw-silver-2025-Hybrid Speed-0-5",
        "name": "'17 Acura NSX",
        "series": "Automative",
        "release": "Hybrid Speed",
        "year": 2025,
        "toyId": "JCB80",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U20N, U21N, U23N, U26N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/d0/JCB80_NSX_o1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/15/2025_JCB80_r1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2717_Acura_NSX"
    }
];