const japaneseclassics2023 = [
    {
        "id": "hw-silver-2023-Japanese Classics-0-1",
        "name": "'98 Honda Prelude",
        "series": "Automative",
        "release": "Japanese Classics",
        "year": 2023,
        "toyId": "HLK16",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/2c/HLK16.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/4e/98_Honda_Prelude_Japanese_Classics_Series_%282023%29.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2798_Honda_Prelude"
    },
    {
        "id": "hw-silver-2023-Japanese Classics-0-2",
        "name": "'90 Acura NSX",
        "series": "Automative",
        "release": "Japanese Classics",
        "year": 2023,
        "toyId": "HLK18",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/de/90_NSX_Japanese_Classics.png",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b3/90_Acura_NSX_Japanese_Classics_Series_%282023%29.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2790_Acura_NSX"
    },
    {
        "id": "hw-silver-2023-Japanese Classics-0-3",
        "name": "'91 Mazda MX-5 Miata",
        "series": "Automative",
        "release": "Japanese Classics",
        "year": 2023,
        "toyId": "HLK17",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/0/0b/HLK17.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/87/91_Mazda_MX5_Miata_Japanese_Classics_Series_%282023%29.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2791_Mazda_MX-5_Miata"
    },
    {
        "id": "hw-silver-2023-Japanese Classics-0-4",
        "name": "Toyota 2000 GT",
        "series": "Automative",
        "release": "Japanese Classics",
        "year": 2023,
        "toyId": "HLK15",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/cd/HLK15.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/c5/Toyota_2000_GT_Japanese_Classics_Series_%282023%29.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Toyota_2000GT"
    },
    {
        "id": "hw-silver-2023-Japanese Classics-0-5",
        "name": "Fairlady 2000",
        "series": "Automative",
        "release": "Japanese Classics",
        "year": 2023,
        "toyId": "HLK14",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R44, R52",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/82/HLK14.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/45/FairLady_2000_Japanese_Classics_Series_%282023%29.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Fairlady_2000"
    }
];