const mopar2023 = [
    {
        "id": "hw-silver-2023-Mopar-0-1",
        "name": "'68 Dodge Dart",
        "series": "Automative",
        "release": "Mopar",
        "year": 2023,
        "toyId": "HLK09",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R36",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/13/1968_Dodge_Dart.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/33/Mopar_2023_%2768_Dodge_Dart_Red_Malaysia_HLK09.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2768_Dodge_Dart"
    },
    {
        "id": "hw-silver-2023-Mopar-0-2",
        "name": "'71 Dodge Challenger",
        "series": "Automative",
        "release": "Mopar",
        "year": 2023,
        "toyId": "HLK12",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R36",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/74/Dodge_Challenger.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/d0/2022_Hot_wheels_MOPAR_71_Dodge_Challenger.png",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_Dodge_Challenger"
    },
    {
        "id": "hw-silver-2023-Mopar-0-3",
        "name": "Dodge Challenger Drift Car",
        "series": "Automative",
        "release": "Mopar",
        "year": 2023,
        "toyId": "HLK13",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R36",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/2a/DodgeChallengerDC.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/dd/Mopar_2023_Dodge_Challenger_Drift_Car_Navy_Blue_Malaysia_HLK13.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Dodge_Challenger_Drift_Car"
    },
    {
        "id": "hw-silver-2023-Mopar-0-4",
        "name": "'15 Dodge Charger SRT",
        "series": "Automative",
        "release": "Mopar",
        "year": 2023,
        "toyId": "HLK10",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R36",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/92/15_Dodge_Charger_Srt.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/3c/2023_Mopar_15_Charger_sealed.JPG",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2715_Dodge_Charger_SRT"
    },
    {
        "id": "hw-silver-2023-Mopar-0-5",
        "name": "Dodge Viper SRT10 ACR",
        "series": "Automative",
        "release": "Mopar",
        "year": 2023,
        "toyId": "HLK11",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): R36",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/0/0d/Dodge_Viper_SRT10.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/96/2023_Mopar_Viper_sealed.JPG",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2708_Viper_SRT10_ACR"
    }
];