const motorcycleclub2024 = [
    {
        "id": "hw-silver-2024-Hot Wheels Motorcycle Club-0-1",
        "name": "Bad Bagger",
        "series": "Automative",
        "release": "Motorcycle Club",
        "year": 2024,
        "toyId": "HRR90",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/86/Hot_Wheels_Motorcycle_Club_2024_Bad_Bagger_Blue_Malaysia_HRR90.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Bad_Bagger"
    },
    {
        "id": "hw-silver-2024-Hot Wheels Motorcycle Club-0-2",
        "name": "BMW K 1300 R",
        "series": "Automative",
        "release": "Motorcycle Club",
        "year": 2024,
        "toyId": "HRR91",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/53/Motorcycle_Club_loose_%283%29.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/bc/Hot_Wheels_Motorcycle_Club_2024_BMW_K_1300_R_Red_Malaysia_HRR91.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/BMW_K_1300_R"
    },
    {
        "id": "hw-silver-2024-Hot Wheels Motorcycle Club-0-3",
        "name": "BMW R nineT Racer",
        "series": "Automative",
        "release": "Motorcycle Club",
        "year": 2024,
        "toyId": "HRR92",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/a5/Motorcycle_Club_loose_%281%29.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/ef/Hot_Wheels_Motorcycle_Club_2024_BMW_R_NineT_Racer_Yellow_Malaysia_HRR92.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/BMW_R_nineT_Racer"
    },
    {
        "id": "hw-silver-2024-Hot Wheels Motorcycle Club-0-4",
        "name": "Ducati Scrambler Hot Wheels Edition",
        "series": "Automative",
        "release": "Motorcycle Club",
        "year": 2024,
        "toyId": "HRR93",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/8b/Motorcycle_Club_loose_%284%29.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/3b/Hot_Wheels_Motorcycle_Club_2024_Ducati_Scrambler_Hot_Wheels_Edition_Silver_Malaysia_HRR93.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Ducati_Scrambler_Hot_Wheels_Edition"
    },
    {
        "id": "hw-silver-2024-Hot Wheels Motorcycle Club-0-5",
        "name": "Honda Monkey Z50",
        "series": "Automative",
        "release": "Motorcycle Club",
        "year": 2024,
        "toyId": "HRR94",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/9c/Motorcycle_Club_loose_%282%29.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/3f/Hot_Wheels_Motorcycle_Club_2024_Honda_Monkey_Z50_Purple_Malaysia_HRR94.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Honda_Monkey_Z50"
    }
];