const rallyracers2026 = [
    {
        "id": "hw-silver-2026-Rally Racers-0-1",
        "name": "'87 Audi quattro",
        "series": "Automative",
        "release": "Rally Racers",
        "year": 2026,
        "toyId": "JKX61",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U41I, U42I, U43I, U44I, U46I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/d1/JKX61_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/47/Silver_Series_2026_Rally_Racers_%2787_Audi_quattro_Indonesia_JKX61.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2787_Audi_quattro"
    },
    {
        "id": "hw-silver-2026-Rally Racers-0-2",
        "name": "Honda S800 Racing",
        "series": "Automative",
        "release": "Rally Racers",
        "year": 2026,
        "toyId": "JKX62",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U41I, U42I, U43I, U44I, U46I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/3c/JKX62_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/28/Honda_S800_Racing.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Honda_S800_Racing"
    },
    {
        "id": "hw-silver-2026-Rally Racers-0-3",
        "name": "Ford Escort RS 2000",
        "series": "Automative",
        "release": "Rally Racers",
        "year": 2026,
        "toyId": "JKX63",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U41I, U42I, U43I, U44I, U47I, U49I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/21/JKX63_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/95/Ford_Escort_RS_2000.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Ford_Escort_RS2000"
    },
    {
        "id": "hw-silver-2026-Rally Racers-0-4",
        "name": "'71 Datsun 510",
        "series": "Automative",
        "release": "Rally Racers",
        "year": 2026,
        "toyId": "JKX64",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U41I, U42I, U43I, U44I, U46I, U48I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b1/JKX64_510_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Silver_Series_2026_Rally_Racers_%2771_Datsun_510_Indonesia_JKX64.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Datsun_Bluebird_510"
    },
    {
        "id": "hw-silver-2026-Rally Racers-0-5",
        "name": "Lancia Rally 037",
        "series": "Automative",
        "release": "Rally Racers",
        "year": 2026,
        "toyId": "JNF48",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U41I, U42I, U43I, U44I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/93/Lancia_Rally_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/3b/2026_Lancia_Rally_r1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Lancia_Rally_037"
    }
];