const summitsurge2026 = [
    {
        "id": "hw-silver-2026-Summit Surge-0-1",
        "name": "Ford Performance SuperVan 4",
        "series": "Automative",
        "release": "Summit Surge",
        "year": 2026,
        "toyId": "JKX66",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U50I, U52I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/91/Silver_Series_2026_Summit_Surge_Ford_Performance_SuperVan_4_Indonesia_JKX66.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Ford_Performance_SuperVan_4"
    },
    {
        "id": "hw-silver-2026-Summit Surge-0-2",
        "name": "McLaren Speedtail",
        "series": "Automative",
        "release": "Summit Surge",
        "year": 2026,
        "toyId": "JKX67",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U50I, U52I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/45/Silver_Series_2026_Summit_Surge_McLaren_Speedtail_Indonesia_JKX67.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/McLaren_Speedtail"
    },
    {
        "id": "hw-silver-2026-Summit Surge-0-3",
        "name": "Aston Martin Vulcan",
        "series": "Automative",
        "release": "Summit Surge",
        "year": 2026,
        "toyId": "JKX68",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U50I, U52I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/5/5f/Silver_Series_2026_Summit_Surge_Aston_Martin_Vulcan_Indonesia_JKX68.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Aston_Martin_Vulcan"
    },
    {
        "id": "hw-silver-2026-Summit Surge-0-4",
        "name": "Jaguar Mk1",
        "series": "Automative",
        "release": "Summit Surge",
        "year": 2026,
        "toyId": "JKX69",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U49I, U50I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/04/Silver_Series_2026_Summit_Surge_Jaguar_Mk1_Indonesia_JKX69.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Jaguar_Mk1"
    },
    {
        "id": "hw-silver-2026-Summit Surge-0-5",
        "name": "'60s Fiat 500D Modificado",
        "series": "Automative",
        "release": "Summit Surge",
        "year": 2026,
        "toyId": "JKX70",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U49I, U50I, U52I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/3c/500D_JKX70.png",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/f9/Silver_Series_2026_Summit_Surge_%2760s_Fiat_500D_Modificado_Indonesia_JKX70.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2760s_Fiat_500D_Modificado"
    }
];