const surfsup2025 = [
    {
        "id": "hw-silver-2025-Surf's Up-0-1",
        "name": "Custom '62 Chevy Pickup",
        "series": "Automative",
        "release": "Surf's Up",
        "year": 2025,
        "toyId": "JCB67",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T50N, U04N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/7f/Silver_Series_2025_Surf%27s_Up_Custom_%2762_Chevy_Pickup_Yellow_Malaysia_JCB67.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_%2762_Chevy"
    },
    {
        "id": "hw-silver-2025-Surf's Up-0-2",
        "name": "Custom '77 Dodge Van",
        "series": "Automative",
        "release": "Surf's Up",
        "year": 2025,
        "toyId": "JCB66",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T50N, U04N, U05N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/88/Custom_%2777_Dodge_Van_2025_Surf%27s_Up.jpeg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/be/Silver_Series_2025_Surf%27s_Up_Custom_%2777_Dodge_Van_Orange_Malaysia_JCB66.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_%2777_Dodge_Van"
    },
    {
        "id": "hw-silver-2025-Surf's Up-0-3",
        "name": "Volkswagen Caddy",
        "series": "Automative",
        "release": "Surf's Up",
        "year": 2025,
        "toyId": "JCB69",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T50N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/27/Silver_Series_2025_Surf%27s_Up_Volkswagen_Caddy_Red_Malaysia_JCB69.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_Caddy"
    },
    {
        "id": "hw-silver-2025-Surf's Up-0-4",
        "name": "Surf Crate",
        "series": "Automative",
        "release": "Surf's Up",
        "year": 2025,
        "toyId": "JCB68",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T50N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/ca/2025_Surf_Crate.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/c8/Silver_Series_2025_Surf%27s_Up_Surf_Crate_Black_Malaysia_JCB68.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Surf_Crate"
    },
    {
        "id": "hw-silver-2025-Surf's Up-0-5",
        "name": "Volkswagen \"Baja Bug\"",
        "series": "Automative",
        "release": "Surf's Up",
        "year": 2025,
        "toyId": "JCB70",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T50N, U04N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/6d/Surf%27s_Up_Bug.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/c3/Silver_Series_2025_Surf%27s_Up_Volkswagen_Baja_Bug_Tan_Malaysia_JCB70.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_%22Baja_Bug%22"
    }
];