const toonedgulf2025 = [
    {
        "id": "hw-silver-2025-Tooned Gulf-0-1",
        "name": "Tooned Volkswagen Golf Mk1",
        "series": "Automative",
        "release": "Tooned Gulf",
        "year": 2025,
        "toyId": "JCB62",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T42, T43, T48, T48N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/53/20250331221020.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/97/Silver_Series_2025_Tooned_Gulf_Tooned_Volkswagen_Golf_MK1_MF_Dark_Blue_Malaysia_JCB62.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Tooned_Volkswagen_Golf_Mk1"
    },
    {
        "id": "hw-silver-2025-Tooned Gulf-0-2",
        "name": "'70 Dodge Charger",
        "series": "Automative",
        "release": "Tooned Gulf",
        "year": 2025,
        "toyId": "JCB63",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T42, T48N, T49",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/47/20250331221031.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a2/Silver_Series_2025_Tooned_Gulf_%2770_Dodge_Charger_Gulf_Racing_Blue_Malaysia_JCB63.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Dodge_Charger_(Tooned)"
    },
    {
        "id": "hw-silver-2025-Tooned Gulf-0-3",
        "name": "Toon'd '83 Chevy Silverado",
        "series": "Automative",
        "release": "Tooned Gulf",
        "year": 2025,
        "toyId": "JCB64",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T42, T43, T49",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/1d/20250331221037.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b0/Silver_Series_2025_Tooned_Gulf_Toon%27d_%2783_Chevy_Silverado_Gulf_Racing_Blue_Malaysia_JCB64.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Toon%27d_%2783_Chevy_Silverado"
    },
    {
        "id": "hw-silver-2025-Tooned Gulf-0-4",
        "name": "Manga Tuner",
        "series": "Automative",
        "release": "Tooned Gulf",
        "year": 2025,
        "toyId": "JCB61",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T43",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/3b/Silver_Series_2025_Tooned_Gulf_Manga_Tuner_White_Malaysia_JCB61.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Manga_Tuner"
    },
    {
        "id": "hw-silver-2025-Tooned Gulf-0-5",
        "name": "'94 Toyota Supra",
        "series": "Automative",
        "release": "Tooned Gulf",
        "year": 2025,
        "toyId": "JCB65",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "New Die-Cast Chassis, Base code(s): T43, T49",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/0/01/20250331221042.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/5/56/Silver_Series_2025_Tooned_Gulf_%2794_Toyota_Supra_White_Malaysia_JCB65.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2794_Toyota_Supra_(Tooned)"
    }
];