const toyota2025 = [
    {
        "id": "hw-silver-2025-Toyota-0-1",
        "name": "'10 Toyota Tundra",
        "series": "Automative",
        "release": "Toyota",
        "year": 2025,
        "toyId": "JCB71",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U07N, U09N, U12N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b2/JCB71.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/d8/Silver_Series_2025_Toyota_%2710_Toyota_Tundra_Black_Malaysia_JCB71.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2710_Toyota_Tundra"
    },
    {
        "id": "hw-silver-2025-Toyota-0-2",
        "name": "'20 Toyota Tacoma",
        "series": "Automative",
        "release": "Toyota",
        "year": 2025,
        "toyId": "JCB72",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U07N, U09N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/5c/JCB72.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/8d/Silver_Series_2025_Toyota_%2720_Toyota_Tacoma_MF_Lime_Malaysia_JCB72.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2720_Toyota_Tacoma"
    },
    {
        "id": "hw-silver-2025-Toyota-0-3",
        "name": "Toyota Land Cruiser",
        "series": "Automative",
        "release": "Toyota",
        "year": 2025,
        "toyId": "JCB73",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U07N, U09N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/4e/JCB73.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a5/Silver_Series_2025_Toyota_Toyota_Land_Cruiser_Red_Malaysia_JCB73.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Toyota_Land_Cruiser"
    },
    {
        "id": "hw-silver-2025-Toyota-0-4",
        "name": "Toyota Land Cruiser 80",
        "series": "Automative",
        "release": "Toyota",
        "year": 2025,
        "toyId": "JCB74",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U07N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/41/JCB74.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/8c/Silver_Series_2025_Toyota_Toyota_Land_Cruiser_80_MF_Evergreen_Malaysia_JCB74.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Toyota_Land_Cruiser_80"
    },
    {
        "id": "hw-silver-2025-Toyota-0-5",
        "name": "Toyota Off-Road Truck",
        "series": "Automative",
        "release": "Toyota",
        "year": 2025,
        "toyId": "JCB75",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U07N, U09N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/67/JCB75.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/fc/Silver_Series_2025_Toyota_Toyota_Off-Road_Truck_Silver_Malaysia_JCB75.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Toyota_Off-Road_Truck"
    }
];