const tubulartrucks2024 = [
    {
        "id": "hw-silver-2024-Tubular Trucks Series-0-1",
        "name": "1980 Dodge Macho Power Wagon",
        "series": "Automative",
        "release": "Tubular Trucks Series",
        "year": 2024,
        "toyId": "HRR95",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T06, T07",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/29/20240407114414.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/4f/20240407114348.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/1980_Dodge_Macho_Power_Wagon"
    },
    {
        "id": "hw-silver-2024-Tubular Trucks Series-0-2",
        "name": "Chevy Blazer 4×4",
        "series": "Automative",
        "release": "Tubular Trucks Series",
        "year": 2024,
        "toyId": "HRR96",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T06, T07",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/46/20240407114420.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/f8/20240407114359.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Blazer_4%C3%974"
    },
    {
        "id": "hw-silver-2024-Tubular Trucks Series-0-3",
        "name": "1985 Ford Bronco",
        "series": "Automative",
        "release": "Tubular Trucks Series",
        "year": 2024,
        "toyId": "HRR97",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T06, T07",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/3c/%2785FordBronco.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/2e/20240407114409.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2785_Ford_Bronco"
    },
    {
        "id": "hw-silver-2024-Tubular Trucks Series-0-4",
        "name": "1987 Toyota Pickup Truck",
        "series": "Automative",
        "release": "Tubular Trucks Series",
        "year": 2024,
        "toyId": "HRR98",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T06, T07",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/cf/%2787ToyotaPickup.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/ff/20240407114404.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/1987_Toyota_Pickup_Truck"
    },
    {
        "id": "hw-silver-2024-Tubular Trucks Series-0-5",
        "name": "1988 Jeep Wagoneer",
        "series": "Automative",
        "release": "Tubular Trucks Series",
        "year": 2024,
        "toyId": "HRR99",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T06, T07",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/6d/20240407114426.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/26/20240407114354.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/1988_Jeep_Wagoneer"
    }
];