const thehotones2026 = [
    {
        "id": "hw-silver-2026-The Hot Ones-1-1",
        "name": "Mazda REPU",
        "series": "The Hot Ones",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX40",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U25N, U30N, U33N, U41N, U43N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/3b/JKX40_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/ce/THO_Mazda_Repu.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Mazda_REPU"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-1-2",
        "name": "'69 Corvette Racer",
        "series": "The Hot Ones",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX41",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U30N, U33N, U41N, U43N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/0/00/JKX41_o1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/00/THO_69_Corvette_Racer.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2769_Corvette_Racer"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-1-3",
        "name": "Nissan Skyline RS (KDR30)",
        "series": "The Hot Ones",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX42",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U24N, U30N, U33N, U41N, U43N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/eb/JKX42_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/14/Nissan_SKyline_RS.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_Skyline_RS_(KDR30)"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-1-4",
        "name": "Porsche 917 LH",
        "series": "The Hot Ones",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX43",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U30N, U41N, U43N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/37/Hot_wheels_Porsche_917_LH.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/41/THO_Porsche_917_LH.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Porsche_917_LH"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-1-5",
        "name": "'60s Fiat 500D Modificado",
        "series": "The Hot Ones",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX44",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U30N, U41N, U43N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/f3/JKX44_HO_Fiat_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/78/Fiat_500D_Modificado.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2760s_Fiat_500D_Modificado"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-1-6",
        "name": "'67 Ford GT40 Mk.IV",
        "series": "The Hot Ones",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX45",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U30N, U33N, U40N, U43N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/ad/JKX45_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/fa/67_Fordt_GT_40_Mk_IV.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2767_Ford_GT40_Mk.IV"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-1-7",
        "name": "Volkswagen T1 Panel Bus",
        "series": "The Hot Ones",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX46",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U25N, U30N, U33N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/98/JKX46_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/7d/VW_T1_Panel_Bus_Combi.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_T1_Panel_Bus"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-1-8",
        "name": "'71 Datsun 510",
        "series": "The Hot Ones",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX55",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U30N, U33N, U37N, U41N, U43N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/ab/JKX55_HO_510_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/0c/THO_Datsun_510.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Datsun_Bluebird_510"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-2-1",
        "name": "Volkswagen Caddy",
        "series": "The Hot Ones",
        "release": "Mix 2",
        "year": 2026,
        "toyId": "JKX48",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U47N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/fd/JKX48_r1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_Caddy"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-2-2",
        "name": "Alfa Romeo GTV6 3.0",
        "series": "The Hot Ones",
        "release": "Mix 2",
        "year": 2026,
        "toyId": "JKX49",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U47N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Alfa_Romeo_GTV6_3.0"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-2-3",
        "name": "'32 Ford",
        "series": "The Hot Ones",
        "release": "Mix 2",
        "year": 2026,
        "toyId": "JKX50",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U47N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2732_Ford"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-2-4",
        "name": "'73 BMW 3.0 CSL Race Car",
        "series": "The Hot Ones",
        "release": "Mix 2",
        "year": 2026,
        "toyId": "JKX51",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U47N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2773_BMW_3.0_CSL_Race_Car"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-2-5",
        "name": "Lamborghini Countach Pace Car",
        "series": "The Hot Ones",
        "release": "Mix 2",
        "year": 2026,
        "toyId": "JKX52",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U47N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Lamborghini_Countach_Pace_Car"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-2-6",
        "name": "'86 Toyota Van",
        "series": "The Hot Ones",
        "release": "Mix 2",
        "year": 2026,
        "toyId": "JKX53",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U47N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/1986_Toyota_Van"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-2-7",
        "name": "'69 Camaro",
        "series": "The Hot Ones",
        "release": "Mix 2",
        "year": 2026,
        "toyId": "JKX54",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U47N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2769_Camaro"
    },
    {
        "id": "hw-silver-2026-The Hot Ones-2-8",
        "name": "'73 Honda Civic Custom",
        "series": "The Hot Ones",
        "release": "Mix 2",
        "year": 2026,
        "toyId": "JKX47",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U47N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2773_Honda_Civic_Custom"
    }
];