const thehotones2025 = [
    {
        "id": "hw-silver-2025-The Hot Ones-0-1",
        "name": "Fiat 500 Topolino (1936)",
        "series": "The Hot Ones",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY69",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T51N, U06N, U07N, U18N, U22N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/3b/JBY69.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/ba/JBY69-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Fiat_500C"
    },
    {
        "id": "hw-silver-2025-The Hot Ones-0-2",
        "name": "Volkswagen T2 Pickup",
        "series": "The Hot Ones",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY70",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T50N, T51N, U06N, U18N, U22N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/9c/JBY70_o-1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/09/JBY70_r1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_T2_Pickup"
    },
    {
        "id": "hw-silver-2025-The Hot Ones-0-3",
        "name": "Custom Otto",
        "series": "The Hot Ones",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY71",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T51N, U06N, U07N, U18N, U22N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/92/JBY71.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/94/JBY71-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_Otto"
    },
    {
        "id": "hw-silver-2025-The Hot Ones-0-4",
        "name": "'70 Toyota Celica",
        "series": "The Hot Ones",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY72",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T51N, U06N, U07N, U22N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/15/1970Celica.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/31/JBY72-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Toyota_Celica"
    },
    {
        "id": "hw-silver-2025-The Hot Ones-0-5",
        "name": "Honda Civic Si",
        "series": "The Hot Ones",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY73",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U06N, U07N, U18N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/ec/HondaCivicSi_TheHotOnes_2025.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a2/JBY73-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Honda_Civic_Si_(2006)"
    },
    {
        "id": "hw-silver-2025-The Hot Ones-0-6",
        "name": "'81 Camaro",
        "series": "The Hot Ones",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY74",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T51N, U06N, U18N, U22N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/26/Camaro_81_pink.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/72/JBY74-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2781_Camaro"
    },
    {
        "id": "hw-silver-2025-The Hot Ones-0-7",
        "name": "Porsche 917 LH",
        "series": "The Hot Ones",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY75",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T51N, U06N, U18N, U22N, U26N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/8c/Porsche_917_lh_gold.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/80/JBY75-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Porsche_917_LH"
    },
    {
        "id": "hw-silver-2025-The Hot Ones-0-8",
        "name": "BMW M1 Procar",
        "series": "The Hot Ones",
        "release": "2025",
        "year": 2025,
        "toyId": "JBY76",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T50N, T51N, U06N, U07N, U18N, U22N",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/ac/BMWM1Procar.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/04/JBY76-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/BMW_M1_Procar"
    }
]