const batman2025 = [
    {
        "id": "hw-silver-2025-Batman-0-1",
        "name": "Batmobile",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY23",
        "seriesNumber": "1/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 1, Base code(s): T37",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/13/Batman_2025_Mix_1_Batmobile_MF_Copper_Thailand_JBY23.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/The_Brave_and_the_Bold_Batmobile"
    },
    {
        "id": "hw-silver-2025-Batman-0-2",
        "name": "Batmobile",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY07",
        "seriesNumber": "2/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 1, Base code(s): T32",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/a0/JBY07.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/31/Batman_2025_Mix_1_Batmobile_Matte_Black_Thailand_JBY07.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Batman_v_Superman_Batmobile"
    },
    {
        "id": "hw-silver-2025-Batman-0-3",
        "name": "Driftsta",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY09",
        "seriesNumber": "3/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 1, Base code(s): T37",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a1/Batman_2025_Mix_1_Driftsta_MF_Green_Thailand_JBY09.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Driftsta"
    },
    {
        "id": "hw-silver-2025-Batman-0-4",
        "name": "Fast FeLion",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY11",
        "seriesNumber": "4/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 1, Base code(s): T37",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/ce/Batman_2025_Mix_1_Fast_Felion_MF_Satin_Blue_Thailand_JBY11.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Fast_FeLion"
    },
    {
        "id": "hw-silver-2025-Batman-0-5",
        "name": "Flight '03",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY10",
        "seriesNumber": "5/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 1, Base code(s): T37",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/40/Batman_2025_Mix_1_Flight_%2703_Red_Thailand_JBY10.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Flight_%2703"
    },
    {
        "id": "hw-silver-2025-Batman-0-6",
        "name": "Batmobile",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY12",
        "seriesNumber": "6/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 2, Base code(s): T44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/7a/Batman_2025_Mix_2_Batmobile_Matte_Gray_Thailand_JBY12.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Batmobile_(2022)"
    },
    {
        "id": "hw-silver-2025-Batman-0-7",
        "name": "Batplane",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY13",
        "seriesNumber": "7/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 2, Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a9/Batman_2025_Mix_2_Batplane_Dark_Blue_Thailand_JBY13.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Batplane"
    },
    {
        "id": "hw-silver-2025-Batman-0-8",
        "name": "Muscle Tone",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY14",
        "seriesNumber": "8/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 2, Base code(s): T44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a0/Batman_2025_Mix_2_Muscle_Tone_MF_Blue_Thailand_JBY14.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Muscle_Tone"
    },
    {
        "id": "hw-silver-2025-Batman-0-9",
        "name": "Barbaric",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY15",
        "seriesNumber": "9/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 2, Base code(s): T44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/14/Batman_2025_Mix_2_Barbaric_MF_Black_Thailand_JBY15.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Barbaric"
    },
    {
        "id": "hw-silver-2025-Batman-0-10",
        "name": "HW Rapid Responder",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY16",
        "seriesNumber": "10/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 2, Base code(s): T44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/83/Batman_2025_Mix_2_HW_Rapid_Responder_Red_Thailand_JBY16.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Rescue_Ranger"
    },
    {
        "id": "hw-silver-2025-Batman-0-11",
        "name": "Classic TV Series Batmobile",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY17",
        "seriesNumber": "11/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 3, New Die-Cast Chassis, Base code(s): U08A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/d5/Silver_Series_Batman_2025_Mix_3_Classic_TV_Series_Batmobile_Thailand_JBY17.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Classic_TV_Series_Batmobile_(Tooned)"
    },
    {
        "id": "hw-silver-2025-Batman-0-12",
        "name": "Arkham Asylum Batmobile",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY18",
        "seriesNumber": "12/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 3, Base code(s): U08A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/63/Silver_Series_Batman_2025_Mix_3_Arkham_Asylum_Batmobile_Thailand_JBY18.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Arkham_Asylum_Batmobile"
    },
    {
        "id": "hw-silver-2025-Batman-0-13",
        "name": "Grand Cross",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY19",
        "seriesNumber": "13/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 3, Base code(s): U08A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/e8/Silver_Series_Batman_2025_Mix_3_Grand_Cross_Thailand_JBY19.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Grand_Cross"
    },
    {
        "id": "hw-silver-2025-Batman-0-14",
        "name": "Track Manga",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY20",
        "seriesNumber": "14/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 3, Base code(s): U05A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/13/Silver_Series_Batman_2025_Mix_3_Track_Manga_Thailand_JBY20.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Track_Manga"
    },
    {
        "id": "hw-silver-2025-Batman-0-15",
        "name": "HW Velocita",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY21",
        "seriesNumber": "15/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 3, Base code(s): U08A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/ee/Silver_Series_Batman_2025_Mix_3_HW_Velocita_Thailand_JBY21.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Velocita"
    },
    {
        "id": "hw-silver-2025-Batman-0-16",
        "name": "Batman Forever Batmobile",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY22",
        "seriesNumber": "16/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 4, Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/49/20250928_194723.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Batman_Forever_Batmobile"
    },
    {
        "id": "hw-silver-2025-Batman-0-17",
        "name": "Justice League Batmobile",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY08",
        "seriesNumber": "17/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 4, Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/ce/20250928_194839.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Justice_League_Batmobile"
    },
    {
        "id": "hw-silver-2025-Batman-0-18",
        "name": "Speed Trap",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY24",
        "seriesNumber": "18/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 4, Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b9/20250928_194732.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Speed_Trap"
    },
    {
        "id": "hw-silver-2025-Batman-0-19",
        "name": "Tail Dragger",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY25",
        "seriesNumber": "19/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 4, Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/bb/20250928_194817.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Tail_Dragger"
    },
    {
        "id": "hw-silver-2025-Batman-0-20",
        "name": "Fast Fish",
        "series": "Batman",
        "release": "",
        "year": 2025,
        "toyId": "JBY26",
        "seriesNumber": "20/20",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Mix 4, Base code(s):",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/86/20250928_194747.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Fast_Fish"
    }
];