const ffbrianoconner2025 = [
    {
        "id": "hw-silver-2025-Fast&Furious-0-1-JBY29",
        "name": "1995 Mitsubishi Eclipse",
        "series": "Fast&Furious",
        "release": "Brian O'Conner",
        "year": 2025,
        "toyId": "JBY29",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T36, T37, T40, T44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/ef/JBY29.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/5/54/PXL_20241205_093319945.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2795_Mitsubishi_Eclipse"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-2-JBY30",
        "name": "Toyota Supra",
        "series": "Fast&Furious",
        "release": "Brian O'Conner",
        "year": 2025,
        "toyId": "JBY30",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T36, T37, T44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/af/JBY30.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/72/F%26F_Supra_%28orange%29_2025.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Toyota_Supra"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-3-JBY31",
        "name": "Nissan Skyline GT-R (BNR34)",
        "series": "Fast&Furious",
        "release": "Brian O'Conner",
        "year": 2025,
        "toyId": "JBY31",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T36, T40, T44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/29/JBY31.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/6a/PXL_20241205_093351976.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_Skyline_GT-R_(BNR34)"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-4-JBY32",
        "name": "1970 Ford Escort RS1600",
        "series": "Fast&Furious",
        "release": "Brian O'Conner",
        "year": 2025,
        "toyId": "JBY32",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T36, T44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/2a/JBY32.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/db/MG_1346.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Ford_Escort_RS1600"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-5-JBY33",
        "name": "Toyota Supra",
        "series": "Fast&Furious",
        "release": "Brian O'Conner",
        "year": 2025,
        "toyId": "JBY33",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T36, T37, T44",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/d1/JBY33.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/ae/White_supra_card.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Toyota_Supra"
    }
];