const ffgraphicremix2025 = [
    {
        "id": "hw-silver-2025-Fast&Furious-0-1-JBY44",
        "name": "Honda S2000",
        "series": "Fast&Furious",
        "release": "Graphic Remix",
        "year": 2025,
        "toyId": "JBY44",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U29A, U31A, U32A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/d0/S20002025ff.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/aa/Silver_Series_2025_Fast_%26_Furious_Graphic_Remix_Honda_S2000_Thailand_JBY44.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Honda_S2000"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-2-JBY47",
        "name": "Lancer Evolution VII",
        "series": "Fast&Furious",
        "release": "Graphic Remix",
        "year": 2025,
        "toyId": "JBY47",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U29A, U31A, U32A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/d1/Evo72025ff.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/fb/Silver_Series_2025_Fast_%26_Furious_Graphic_Remix_Lancer_Evolution_VII_Thailand_JBY47.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Lancer_Evolution_VII"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-3-JBY46",
        "name": "Volkswagen Jetta MK3",
        "series": "Fast&Furious",
        "release": "Graphic Remix",
        "year": 2025,
        "toyId": "JBY46",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U29A, U31A, U32A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/38/Jetta2025ff.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/41/JBY46_Jetta_r1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_Jetta_MK3"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-4-JBY48",
        "name": "Nissan Silvia (S15)",
        "series": "Fast&Furious",
        "release": "Graphic Remix",
        "year": 2025,
        "toyId": "JBY48",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U29A, U31A, U32A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/bd/S152025ff.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/99/Silver_Series_2025_Fast_%26_Furious_Graphic_Remix_Nissan_Silvia_%28S15%29_Thailand_JBY48.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_Silvia_(S15)"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-5-JBY45",
        "name": "Custom Acura Integra Sedan GSR",
        "series": "Fast&Furious",
        "release": "Graphic Remix",
        "year": 2025,
        "toyId": "JBY45",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U29A, U31A, U32A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/e5/Acura2025ff.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/c6/Silver_Series_2025_Fast_%26_Furious_Graphic_Remix_Custom_Acura_Integra_Sedan_GSR_Thailand_JBY45.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_Acura_Integra_Sedan_GSR"
    }
];