const ffracingcourse2025 = [
    {
        "id": "hw-silver-2025-Fast&Furious-0-1-JBY39",
        "name": "Honda Civic EG",
        "series": "Fast&Furious",
        "release": "Racing Course",
        "year": 2025,
        "toyId": "JBY39",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "New Casting, Base code(s): U12A, U14A, U18A, U19A, U26A, U27A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/67/1992HondaCivicEG.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/91/JBY39.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Honda_Civic_EG_(2025)"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-2-JBY40",
        "name": "1996 Acura Integra GSR",
        "series": "Fast&Furious",
        "release": "Racing Course",
        "year": 2025,
        "toyId": "JBY40",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "New Casting, Base code(s): U12A, U17A, U19A, U21A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/19/1996AcuraIntegraGSR.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b4/Silver_Series_2025_Fast_%26_Furious_Racing_Course_1996_Acura_Integra_GSR_Thailand_JBY40.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/1996_Acura_Integra_GSR"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-3-JBY41",
        "name": "Datsun 240Z Custom",
        "series": "Fast&Furious",
        "release": "Racing Course",
        "year": 2025,
        "toyId": "JBY41",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U12A, U19A, U20A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/31/1975Datsun240Z.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b2/Silver_Series_2025_Fast_%26_Furious_Racing_Course_Datsun_240Z_Custom_Thailand_JBY41.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Datsun_240Z_Custom"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-4-JBY42",
        "name": "1966 Chevy Nova",
        "series": "Fast&Furious",
        "release": "Racing Course",
        "year": 2025,
        "toyId": "JBY42",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U12A, U19A, U21A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/ee/1966Nova.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/fd/Silver_Series_2025_Fast_%26_Furious_Racing_Course_1966_Chevy_Nova_Thailand_JBY42.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2766_Chevy_Nova"
    },
    {
        "id": "hw-silver-2025-Fast&Furious-0-5-JBY43",
        "name": "Bugatti Veyron",
        "series": "Fast&Furious",
        "release": "Racing Course",
        "year": 2025,
        "toyId": "JBY43",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U12A, U19A, U20A, U26A, U27A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/82/2011BugattiVeyronEB.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/2d/JBY43.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Bugatti_Veyron_(2023)"
    }
];