const neonspeeders2025 = [
    {
        "id": "hw-silver-2025-Neon Speeders-3-1",
        "name": "Custom '70 Honda N600",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2025,
        "toyId": "JBY92",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T37, T40",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/44/JBY92.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/68/Neon_Speeders_2025_Mix_1_Custom_%2770_Honda_N600_Neon_Yellow_Thailand_JBY92.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_%2770_Honda_N600"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-3-2",
        "name": "Custom Volkswagen Beetle",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2025,
        "toyId": "JBY93",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T37, T40, T47A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c3/HW_2025_Neon_Speeders_Custom_Beetle.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/63/Neon_Speeders_2025_Mix_1_Custom_Volkswagen_Beetle_Neon_Green_Thailand_JBY93.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_Volkswagen_Beetle"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-3-3",
        "name": "Nissan Silvia (S13)",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2025,
        "toyId": "JBY94",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T35, T37, T40",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/ea/20241218233344.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a2/20241218233358.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_Silvia_(S13)"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-3-4",
        "name": "Mad Manga",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2025,
        "toyId": "JBY95",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T37, T40",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c8/JBY95.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/15/Neon_Speeders_2025_Mix_1_Mad_Manga_Matte_Black_Thailand_JBY95.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Mad_Manga"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-3-5",
        "name": "Mini Cooper S Challenge",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2025,
        "toyId": "JBY96",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T36, T37",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/48/2025_Mini_Cooper_S_Challenge.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/e2/Neon_Speeders_2025_Mix_1_Mini_Cooper_S_Challenge_Neon_Orange_Thailand_JBY96.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Mini_Cooper_S_Challenge"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-3-6",
        "name": "'70 Chevy Chevelle SS",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2025,
        "toyId": "JBY97",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T37, T40, T47, T47A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/20/JBY97.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/c8/Neon_Speeders_2025_Mix_1_%2770_Chevy_Chevelle_Matte_Black_Thailand_JBY97.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Chevy_Chevelle_SS"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-3-7",
        "name": "'70 Dodge Hemi Challenger",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2025,
        "toyId": "JBY98",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T37, T40, T47A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/eb/20241218233332.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/60/20241218233418.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Dodge_Hemi_Challenger"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-3-8",
        "name": "Porsche 993 GT2",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2025,
        "toyId": "JBY99",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T37, T44, T47A",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/82/20241218233338.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/11/20241218233412.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Porsche_993_GT2"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-4-1",
        "name": "'98 Honda Prelude",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2025,
        "toyId": "JCB00",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U10I, U11I, U13I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/2f/JCB00.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/99/JCB00-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2798_Honda_Prelude"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-4-2",
        "name": "Mazda RX-7",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2025,
        "toyId": "JCB01",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U09I, U15I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/a2/JCB01.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/17/Neon_Speeders_2025_Mix_2_Mazda_RX-7_Neon_Pink_Indonesia_JCB01.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Mazda_RX-7"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-4-3",
        "name": "2008 Lancer Evolution",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2025,
        "toyId": "JCB02",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U10I, U15I, U16I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/d7/JCB02.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/c6/JCB02-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/2008_Lancer_Evolution"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-4-4",
        "name": "Toyota AE-86 Corolla",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2025,
        "toyId": "JCB03",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U09I, U11I, U16I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/74/JCB03.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/05/JCB03-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Toyota_AE-86_Corolla"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-4-5",
        "name": "Datsun Fairlady 2000",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2025,
        "toyId": "JCB04",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U06I, U09I, U10I, U13I, U15I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/d9/JCB04.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/78/JCB04-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Fairlady_2000"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-4-6",
        "name": "Porsche 934 Turbo RSR",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2025,
        "toyId": "JCB05",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U09I, U10I, U11I, U12I, U13I, U16I, U27I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/bd/JCB05.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/ce/JCB05-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Porsche_934_Turbo_RSR"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-4-7",
        "name": "2018 COPO Camaro SS",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2025,
        "toyId": "JCB06",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U10I, U15I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/5b/Neon_Camaro.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/e2/JCB06-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2718_COPO_Camaro_SS"
    },
    {
        "id": "hw-silver-2025-Neon Speeders-4-8",
        "name": "BMW 2002",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2025,
        "toyId": "JCB07",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U06I, U09I, U10I, U11I, U13I, U15I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/8c/BMW_Neon.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/9/9e/Neon_Speeders_2025_Mix_2_BMW_2002_Indonesia_JCB07.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/BMW_2002"
    }
]