const neonspeeders2026 = [
    {
        "id": "hw-silver-2026-Neon Speeders-5-1",
        "name": "Volvo 850 Estate",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX93",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U31I, U32I, U34I, U40I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/4b/JKX93.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/39/Neon_Speeders_2026_Mix_1_Volvo_850_Estate_Indonesia_JKX93.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volvo_850_Estate"
    },
    {
        "id": "hw-silver-2026-Neon Speeders-5-2",
        "name": "Custom Ford Maverick",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX94",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U31I, U33I, U40I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/d/d4/JKX94.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b4/Neon_Speeders_2026_Mix_1_Custom_Ford_Maverick_Indonesia_JKX94.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_Ford_Maverick"
    },
    {
        "id": "hw-silver-2026-Neon Speeders-5-3",
        "name": "'62 Corvette",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX95",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U31I, U33I, U40I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/4/4c/JKX95.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/1d/%2762_Corvette_Neon_Speeders_2026.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2762_Corvette"
    },
    {
        "id": "hw-silver-2026-Neon Speeders-5-4",
        "name": "'64 Chevy Nova Gasser",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX96",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U31I, U33I, U40I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/74/JKX96.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/dc/Neon_Nova_Gasser_%281%29.JPG",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2764_Nova_Wagon_Gasser"
    },
    {
        "id": "hw-silver-2026-Neon Speeders-5-5",
        "name": "'70 Dodge Hemi Challenger",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX97",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U31I, U33I, U40I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/ab/JKX97.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b0/Neon_Speeders_2026_Mix_1_%2770_Dodge_HEMI_Challenger_Indonesia_JKX97.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Dodge_Hemi_Challenger"
    },
    {
        "id": "hw-silver-2026-Neon Speeders-5-6",
        "name": "Volkswagen SP2",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX98",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U29I, U30I, U31I, U33I, U34I, U40I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/f3/JKX98.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/ce/Neon_VW_SP2_%281%29.JPG",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_SP2"
    },
    {
        "id": "hw-silver-2026-Neon Speeders-5-7",
        "name": "'85 Honda CR-X",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKX99",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U33I, U40I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/1f/JKX99.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/7f/Neon_Speeders_2026_Mix_1_%2785_Honda_CR-X_Indonesia_JKX99.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/1985_Honda_CR-X"
    },
    {
        "id": "hw-silver-2026-Neon Speeders-5-8",
        "name": "'71 Porsche 911",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2026,
        "toyId": "JKY00",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U32I, U33I, U34I, U40I, U44I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/39/JKY00.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/2d/Neon_Speeders_2026_Mix_1_%2771_Porsche_911_Indonesia_JKY00.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_Porsche_911"
    }
];