const neonspeeders2023 = [
    {
        "id": "hw-silver-2023-Neon Speeders-0-1",
        "name": "Ford Focus RS",
        "series": "Neon Speeders",
        "release": "",
        "year": 2023,
        "toyId": "HLH73",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S07, S08",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/7f/HLH73.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/27/2023_Neon_Speeders.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Ford_Focus_RS"
    },
    {
        "id": "hw-silver-2023-Neon Speeders-0-2",
        "name": "Volkswagen Golf Mk7",
        "series": "Neon Speeders",
        "release": "",
        "year": 2023,
        "toyId": "HLH74",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S08, S09",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/1f/NSGolf.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/4d/Neon_Seepders_2023_2-8.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_Golf_Mk7"
    },
    {
        "id": "hw-silver-2023-Neon Speeders-0-3",
        "name": "2017 Nissan GT-R (R35)",
        "series": "Neon Speeders",
        "release": "",
        "year": 2023,
        "toyId": "HLH75",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S08",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/ef/NS2017GT-R.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/ff/Neon_Speeders_2023_3-8.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2717_Nissan_GT-R_(R35)"
    },
    {
        "id": "hw-silver-2023-Neon Speeders-0-4",
        "name": "'99 Honda Civic Type R (EK9)",
        "series": "Neon Speeders",
        "release": "",
        "year": 2023,
        "toyId": "HLH76",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S08",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/75/NSEK9.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/bb/Neon_Speeders_2023_4-8.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2799_Honda_Civic_Type_R_(EK9)"
    },
    {
        "id": "hw-silver-2023-Neon Speeders-0-5",
        "name": "GT Hunter",
        "series": "Neon Speeders",
        "release": "",
        "year": 2023,
        "toyId": "HLH77",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S08",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/8e/NSGTHunter.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b4/Neon_Speeders_2023_5-8.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/GT_Hunter"
    },
    {
        "id": "hw-silver-2023-Neon Speeders-0-6",
        "name": "SRT Viper GTS-R",
        "series": "Neon Speeders",
        "release": "",
        "year": 2023,
        "toyId": "HLH78",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S08",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/73/NSViper.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/1/16/Neon_Speeders_2023_6-8.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/SRT_Viper_GTS-R"
    },
    {
        "id": "hw-silver-2023-Neon Speeders-0-7",
        "name": "Rally Cat",
        "series": "Neon Speeders",
        "release": "",
        "year": 2023,
        "toyId": "HLH79",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S08",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/1/17/NSRallyCat.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a4/Neon_Speedere_2023_7-8.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Rally_Cat"
    },
    {
        "id": "hw-silver-2023-Neon Speeders-0-8",
        "name": "2016 BMW M2",
        "series": "Neon Speeders",
        "release": "",
        "year": 2023,
        "toyId": "HLH80",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S08, S09",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/0/04/NSM2.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/f8/Neon_Speeders_2023_8-8.jpeg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/2016_BMW_M2"
    }
]