const neonspeeders2024 = [
    {
        "id": "hw-silver-2024-Neon Speeders-1-1",
        "name": "'70 Toyota Celica",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRW67",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S41, S44, S48",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b3/1970ToyotaCelica.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a0/224222450.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Toyota_Celica"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-1-2",
        "name": "Datsun 510 Wagon",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRW68",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S41, S44, S48",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/71/DatsunWagon.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/f6/231224222442.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_Datsun_Bluebird_510_Wagon"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-1-3",
        "name": "Nissan Skyline 2000GT-R",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRW69",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S41, S44, S48",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/65/NeonKenmeri.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/5/5a/231224222454.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_Skyline_2000GT-R"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-1-4",
        "name": "'95 Mazda RX-7 Drift",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRW70",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S43, S45, S48",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/31/MazdaRX-7DriftCar.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/41/31224222437.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2795_Mazda_RX-7_Drift"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-1-5",
        "name": "'95 Mitsubishi Eclipse",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRW71",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S44, S48",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/50/1995MitsubishiEclipse.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/87/0231224222446.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2795_Mitsubishi_Eclipse"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-1-6",
        "name": "Honda S2000",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRW72",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S41, S44, S48",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/5e/2002HondaS2000.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/37/0231224222427.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Honda_S2000"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-1-7",
        "name": "Custom '01 Acura Integra GSR",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRW73",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S41, S44, S48",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/9a/2001HondaIntegra.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a3/31224222458.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_%2701_Acura_Integra_GSR"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-1-8",
        "name": "Nissan 350Z",
        "series": "Neon Speeders",
        "release": "Mix 1",
        "year": 2024,
        "toyId": "HRW74",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S41, S44, S48",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/ab/2005Nissan350Z.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/ca/31224222502.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Nissan_350Z"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-2-1",
        "name": "Porsche 911 GT3 Cup",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRW75",
        "seriesNumber": "1/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T09, T13, T14",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/ff/2024-Neon_Speeders_1-8_HRW75_GT3_CUP_open-1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a3/Neon_Speeders_2024_Mix_2_Porsche_911_GT3_Cup_Neon_Pink_Thailand_HRW75.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Porsche_911_GT3_Cup"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-2-2",
        "name": "McLaren F1 GTR",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRW76",
        "seriesNumber": "2/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T09, T11",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/bd/McLaren_F1_GTR_Neon.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/6f/Neon_Speeders_2024_Mix_2_McLaren_F1_GTR_Matte_Black_Thailand_HRW76.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/McLaren_F1_GTR"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-2-3",
        "name": "Ford GT",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRW77",
        "seriesNumber": "3/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T09, T10, T11",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/8a/HRW77.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/6/6f/Neon_Speeders_2024_Mix_2_Ford_GT_Neon_Yellow_Thailand_HRW77.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Ford_GT"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-2-4",
        "name": "BMW M3 GT2",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRW78",
        "seriesNumber": "4/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T09, T11, T13",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/f8/2024_HRW78_BMW_M3_GT2_o-4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/3f/Neon_Speeders_2024_Mix_2_BMW_M3_GT2_Neon_Orange_Thailand_HRW78.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/BMW_M3_GT2"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-2-5",
        "name": "'16 Mercedes-AMG GT3",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRW79",
        "seriesNumber": "5/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T11, T14",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/93/2024_HRW79_Mercedes-AMG_GT3_o-1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/f/fe/Neon_Speeders_2024_Mix_2_%2716_Mercedes-AMG_GT3_Metalflake_Black_Thailand_HRW79.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2716_Mercedes-AMG_GT3"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-2-6",
        "name": "'15 Dodge Challenger SRT Hellcat",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRW80",
        "seriesNumber": "6/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T09, T11, T13",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/0/0f/HRW80.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/0b/Neon_Speeders_2024_Mix_2_%2715_Dodge_Challenger_SRT_Hellcat_Matte_Black_Thailand_HRW80.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2715_Dodge_Challenger_SRT"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-2-7",
        "name": "Corvette C7 Z06",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRW81",
        "seriesNumber": "7/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T09, T11",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c1/2024-Neon_Speeders_HRW81_C7_Z06_o-1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/8f/Neon_Speeders_2024_Mix_2_Corvette_C7_Z06_Matte_Neon_Green_Thailand_HRW81.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Corvette_C7_Z06"
    },
    {
        "id": "hw-silver-2024-Neon Speeders-2-8",
        "name": "'16 Cadillac ATS-V R",
        "series": "Neon Speeders",
        "release": "Mix 2",
        "year": 2024,
        "toyId": "HRW82",
        "seriesNumber": "8/8",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T09, T11",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/34/2024-Neon_Speeders_HRW82_o-1.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/d2/Neon_Speeders_2024_Mix_2_%2716_Cadillac_ATS-V_R_Black_Thailand_HRW82.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2716_Cadillac_ATS-V_R"
    }
]