const pontiac100an2026 = [
    {
        "id": "hw-silver-2026-Pontiac 100th Anniversary-0-1",
        "name": "'84 Pontiac Firebird",
        "series": "Celebrations",
        "release": "Pontiac 100th Anniversary",
        "year": 2026,
        "toyId": "JKY09",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U32I, U33I, U34I, U35I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c9/Pontiac_100th_loose_Firebird.JPG",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/cd/JKY09-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2784_Pontiac_Firebird"
    },
    {
        "id": "hw-silver-2026-Pontiac 100th Anniversary-0-2",
        "name": "'06 Pontiac GTO",
        "series": "Celebrations",
        "release": "Pontiac 100th Anniversary",
        "year": 2026,
        "toyId": "JKY10",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U32I, U33I, U34I, U35I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/81/009-069.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/d0/JKY10-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2706_Pontiac_GTO"
    },
    {
        "id": "hw-silver-2026-Pontiac 100th Anniversary-0-3",
        "name": "'65 Pontiac Bonneville",
        "series": "Celebrations",
        "release": "Pontiac 100th Anniversary",
        "year": 2026,
        "toyId": "JKY12",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U32I, U33I, U34I, U35I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/9f/1965Bonneville.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/48/JKY12-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2765_Pontiac_Bonneville"
    },
    {
        "id": "hw-silver-2026-Pontiac 100th Anniversary-0-4",
        "name": "'70 Pontiac GTO Judge",
        "series": "Celebrations",
        "release": "Pontiac 100th Anniversary",
        "year": 2026,
        "toyId": "JKY13",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U32I, U33I, U34I, U35I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/0/01/001-096.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/cd/JKY13-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2770_Pontiac_GTO_Judge"
    },
    {
        "id": "hw-silver-2026-Pontiac 100th Anniversary-0-5",
        "name": "'66 Pontiac GTO",
        "series": "Celebrations",
        "release": "Pontiac 100th Anniversary",
        "year": 2026,
        "toyId": "JKY14",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U32I, U33I, U35I, U44I, U45I, U50I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/0/07/002-108.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/3/3a/JKY14-carded.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2766_Pontiac_GTO"
    }
];