const vintageracingclud2024 = [
    {
        "id": "hw-silver-2024-Vintage Racing Club-0-1",
        "name": "1954 Mercedes-Benz 300 SL",
        "series": "Vintage",
        "release": "Vintage Racing Club - Mix 1",
        "year": 2024,
        "toyId": "HRV00",
        "seriesNumber": "1/6",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Metal base, , Base code(s): S41, S42, S44, S45, S46",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/63/2024-VRCnHRV00_%2754_Mercedes-Benz_300_SL_open-4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/7/76/Vintage_Racing_Club_2024_1954_Mercedes-Benz_300_SL_White_Thailand_HRV00.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Mercedes-Benz_300_SL"
    },
    {
        "id": "hw-silver-2024-Vintage Racing Club-0-2",
        "name": "1955 Corvette",
        "series": "Vintage",
        "release": "Vintage Racing - Club Mix 1",
        "year": 2024,
        "toyId": "HRV01",
        "seriesNumber": "2/6",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Metal base, , Base code(s): S41, S42, S44, S46",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/f2/40113013321.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/df/Vintage_Racing_Club_2024_1955_Corvette_Baby_Blue_Thailand_HRV01.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2755_Corvette"
    },
    {
        "id": "hw-silver-2024-Vintage Racing Club-0-3",
        "name": "BMW 2002",
        "series": "Vintage",
        "release": "Vintage Racing Club - Mix 1",
        "year": 2024,
        "toyId": "HRV02",
        "seriesNumber": "3/6",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S41, S42, S44, S47",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/5/5e/2024-VRC_HRV02_BMW_2002_open-4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Vintage_Racing_Club_2024_BMW_2002_White_Thailand_HRV02.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/BMW_2002"
    },
    {
        "id": "hw-silver-2024-Vintage Racing Club-0-4",
        "name": "1971 Lamborghini Miura SV",
        "series": "Vintage",
        "release": "Vintage Racing Club - Mix 1",
        "year": 2024,
        "toyId": "HRV03",
        "seriesNumber": "4/6",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S41, S42, S44, S47",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/e/eb/1971RacingMiura.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/c/c7/Vintage_Racing_Club_2024_1971_Lamborghini_Miura_SV_Gold_Thailand_HRV03.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_Lamborghini_Miura_SV"
    },
    {
        "id": "hw-silver-2024-Vintage Racing Club-0-5",
        "name": "1971 Porsche 911",
        "series": "Vintage",
        "release": "Vintage Racing Club - Mix 1",
        "year": 2024,
        "toyId": "HRV04",
        "seriesNumber": "5/6",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): S41, S42, S45, S47",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b9/2024-VRC_HRV04_%2771_911_open-4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/0c/Vintage_Racing_Club_2024_1971_Porsche_911_Green_Thailand_HRV04.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_Porsche_911"
    },
    {
        "id": "hw-silver-2024-Vintage Racing Club-0-6",
        "name": "1967 Camaro",
        "series": "Vintage",
        "release": "Vintage Racing Club - Mix 1",
        "year": 2024,
        "toyId": "HRV05",
        "seriesNumber": "6/6",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Opening hood, , Base code(s); S43",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/61/2024-VRC_HRV05_%2767_Camaro_o-2b.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/0e/2024-VRC_HRV05_%2767_Camaro_r-1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2767_Camaro"
    },
    {
        "id": "hw-silver-2024-Vintage Racing Club-1-1",
        "name": "1962 Corvette",
        "series": "Vintage",
        "release": "Vintage Racing Club - Mix 2",
        "year": 2024,
        "toyId": "HRV06",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T05, T06",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/f/f4/20240407114343.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a4/Vintage_Racing_Club_2024_Mix_2_1962_Corvette_Light_Gray_Thailand_HRV06.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2762_Corvette"
    },
    {
        "id": "hw-silver-2024-Vintage Racing Club-1-2",
        "name": "Toyota 2000GT",
        "series": "Vintage",
        "release": "Vintage Racing Club - Mix 2",
        "year": 2024,
        "toyId": "HRV07",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T04, T05, T06, T09",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/HRV07.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/89/Vintage_Racing_Club_2024_Mix_2_Toyota_2000GT_Red_Thailand_HRV07.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Toyota_2000GT"
    },
    {
        "id": "hw-silver-2024-Vintage Racing Club-1-3",
        "name": "1969 Ford Mustang Boss 302",
        "series": "Vintage",
        "release": "Vintage Racing Club - Mix 2",
        "year": 2024,
        "toyId": "HRV08",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T05, T06",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/7/7e/HRV08.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/eb/Vintage_Racing_Club_2024_Mix_2_1969_Ford_Mustang_Boss_302_Yellow_Thailand_HRV08.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2769_Ford_Mustang_Boss_302"
    },
    {
        "id": "hw-silver-2024-Vintage Racing Club-1-4",
        "name": "Custom Ford Maverick",
        "series": "Vintage",
        "release": "Vintage Racing Club - Mix 2",
        "year": 2024,
        "toyId": "HRV09",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T04, T05, T06",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/83/20240407114337.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/b/b0/Vintage_Racing_Club_2024_Mix_2_Custom_Ford_Maverick_Black_Thailand_HRV09.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_Ford_Maverick"
    },
    {
        "id": "hw-silver-2024-Vintage Racing Club-1-5",
        "name": "Custom Datsun 240Z",
        "series": "Vintage",
        "release": "Vintage Racing Club - Min 2024",
        "year": 2024,
        "toyId": "HRV10",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): T05, T06, T10",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/6/60/20240407114255.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/05/Vintage_Racing_Club_2024_Mix_2_Custom_Datsun_240Z_Orange_Thailand_HRV10.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_Datsun_240Z"
    }
];
