const vintage2026 = [
    {
        "id": "hw-silver-2026-Vintage Club-0-1",
        "name": "'65 Mustang 2+2 Fastback",
        "series": "Vintage",
        "release": "Vintage Club - Mix 1",
        "year": 2026,
        "toyId": "JKY31",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U32I, U34I, U40I, U41I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b0/WhatsApp_Image_2025-11-01_at_16.24.15_7173c688.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a9/JKY31_r1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2765_Mustang_2%2B2_Fastback"
    },
    {
        "id": "hw-silver-2026-Vintage Club-0-2",
        "name": "Sooo Fast",
        "series": "Vintage",
        "release": "Vintage Club - Mix 1",
        "year": 2026,
        "toyId": "JKY32",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U34I, U41I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/8/80/WhatsApp_Image_2025-11-01_at_16.24.15_f70071f4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/e0/JKY32_r1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Sooo_Fast"
    },
    {
        "id": "hw-silver-2026-Vintage Club-0-3",
        "name": "Mod Rod",
        "series": "Vintage",
        "release": "Vintage Club - Mix 1",
        "year": 2026,
        "toyId": "JKY33",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U34I, U41I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/a/ac/WhatsApp_Image_2025-11-01_at_16.24.16_f7667015.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/d/d2/JKY33_r1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Mod_Rod"
    },
    {
        "id": "hw-silver-2026-Vintage Club-0-4",
        "name": "'71 Porsche 911",
        "series": "Vintage",
        "release": "Vintage Club - Mix 1",
        "year": 2026,
        "toyId": "JKY34",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U29I, U31I, U34I, U41I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c9/Porsche_911_%22Vintage_Club%22.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/8e/JKY34_r1.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2771_Porsche_911"
    },
    {
        "id": "hw-silver-2026-Vintage Club-0-5",
        "name": "Volkswagen \"Classic Bug\"",
        "series": "Vintage",
        "release": "Vintage Club - Mix 1",
        "year": 2026,
        "toyId": "JKY35",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base reads \"Classis Bug\", Base code(s): U31I, U34I, U40I, U41I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/9/97/WhatsApp_Image_2025-11-01_at_16.24.16_1730feed.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/a/a4/JKY35_r1Z.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Volkswagen_%22Classic_Bug%22"
    },
    {
        "id": "hw-silver-2026-Vintage Club-1-1",
        "name": "BMW 507",
        "series": "Vintage",
        "release": "Vintage Club - Mix 2",
        "year": 2026,
        "toyId": "JKY26",
        "seriesNumber": "1/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U49I, U50I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/3/35/JKY26_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/0/0a/Silver_Series_2026_Vintage_Club_Mix_2_BMW_507_Indonesia_JKY26.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/BMW_507"
    },
    {
        "id": "hw-silver-2026-Vintage Club-1-2",
        "name": "Custom '70 Honda N600",
        "series": "Vintage",
        "release": "Vintage Club - Mix 2",
        "year": 2026,
        "toyId": "JKY27",
        "seriesNumber": "2/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U49I, U50I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/2/2c/JKY27_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/e/e9/Silver_Series_2026_Vintage_Club_Mix_2_Custom_%2770_Honda_N600_Indonesia_JKY27.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Custom_%2770_Honda_N600"
    },
    {
        "id": "hw-silver-2026-Vintage Club-1-3",
        "name": "Alfa Romeo GTV6 30",
        "series": "Vintage",
        "release": "Vintage Club - Mix 2",
        "year": 2026,
        "toyId": "JKY30",
        "seriesNumber": "3/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U49I, U50I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/4/42/Silver_Series_2026_Vintage_Club_Mix_2_Alfa_Romeo_GTV6_30_Indonesia_JKY30.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Alfa_Romeo_GTV6_3.0"
    },
    {
        "id": "hw-silver-2026-Vintage Club-1-4",
        "name": "'65 Ford Galaxie",
        "series": "Vintage",
        "release": "Vintage Club - Mix 2",
        "year": 2026,
        "toyId": "JKY29",
        "seriesNumber": "4/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U49I, U50I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/b/b5/Image_Not_Available.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/2/27/Silver_Series_2026_Vintage_Club_Mix_2_%2765_Ford_Galaxie_Indonesia_JKY29.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/%2765_Ford_Galaxie"
    },
    {
        "id": "hw-silver-2026-Vintage Club-1-5",
        "name": "Porsche 356 Outlaw",
        "series": "Vintage",
        "release": "Vintage Club - Mix 2",
        "year": 2026,
        "toyId": "JKY28",
        "seriesNumber": "5/5",
        "mainlineNumber": "",
        "rarity": "Silver",
        "collectionType": "silver",
        "extraNote": "Base code(s): U49I, U50I",
        "imageUrl": "https://static.wikia.nocookie.net/hotwheels/images/c/c6/JKY28_o4.jpg",
        "imageUrlCardboard": "https://static.wikia.nocookie.net/hotwheels/images/8/8a/Silver_Series_2026_Vintage_Club_Mix_2_Porsche_356_Outlaw_Indonesia_JKY28.jpg",
        "wikiLink": "https://hotwheels.fandom.com/wiki/Porsche_356_Outlaw"
    }
];